# Generated by Django 3.1 on 2020-08-22 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.BooleanField(default=True)),
                ('Fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('Usuario_mod', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('apellido', models.CharField(max_length=250)),
                ('dirección', models.CharField(max_length=250)),
                ('teléfono', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('Usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
