# Generated by Django 3.1 on 2020-12-04 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0007_auto_20200820_2137'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprasEnc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.BooleanField(default=True)),
                ('Fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('Usuario_mod', models.IntegerField(blank=True, null=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('fecha_factura', models.DateField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('numero_factura', models.CharField(max_length=100)),
                ('sub_total', models.FloatField(default=0)),
                ('descuento', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('Usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proveedor_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor')),
            ],
            options={
                'verbose_name': 'Encabezado Compra',
                'verbose_name_plural': 'Encabezado Compras',
            },
        ),
        migrations.CreateModel(
            name='ComprasDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.BooleanField(default=True)),
                ('Fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('Usuario_mod', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.BigIntegerField(default=0)),
                ('precio_prv', models.FloatField(default=0)),
                ('sub_total', models.FloatField(default=0)),
                ('descuento', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('costo', models.FloatField(default=0)),
                ('Usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.comprasenc')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
